name: ezTarball
permissions:
  contents: write
on:
  push:
    paths:
      - 'template/**'

jobs:
  ngambil-file-yg-gk-ngotak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tar files
        run: |
          tar -czvf template.tar.gz ./template/*
          ls -la

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "ezTarball (for 'template' folder)"
          git add template.tar.gz
          git commit -m "Add tarred template files"
          git push
