name: ezZipper (for template folders)

on:
  push:
    paths:
      - 'template/**'

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip files
        run: |
          zip -r template.zip template/*

      - name: Move zip file to the root directory
        run: mv template.zip ../template.zip

      - name: Commit and push
        run: |
          git add template.zip
          git commit -m "Add zipped template files"
          git push

